app/user_system/models.py
from datetime import datetime
from flask import url_for, redirect
from flask_login import UserMixin, current_user
from flask_admin.contrib.sqla import ModelView
from app import db, admin, bcrypt


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    role = db.Column(db.String(60))


class UserView(ModelView):
    column_exclude_list = ["password"]
    can_edit = False
    can_delete = False

    def on_model_change(self, form, model, is_created):
        hashed_password = bcrypt.generate_password_hash(model.password).decode("utf-8")
        model.password = hashed_password

    def is_accessible(self):
        return current_user.is_authenticated

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for("user_system.login"))


admin.add_view(UserView(User, db.session))


class TestModel(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    test_string = db.Column(db.String(256))
    test_int = db.Column(db.Integer)
    test_date = db.Column(db.DateTime, default=datetime.utcnow())
    test_bool = db.Column(db.Boolean)


class TestModelView(ModelView):
    column_filters = [
        "id",
        "test_string",
        "test_int",
        "test_date",
        "test_bool",
    ]
    column_searchable_list = [
        "id",
        "test_string",
        "test_int",
        "test_date",
        "test_bool",
    ]

    def is_accessible(self):
        return current_user.is_authenticated

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for("user_system.login"))


admin.add_view(TestModelView(TestModel, db.session))

app/__init__.py
import logging
from flask import Flask, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager, current_user
from flask_admin import Admin, expose, AdminIndexView
from flask_restx import Api
from app.config import config


# set up flask-sqlalchemy
# https://flask-sqlalchemy.palletsprojects.com/en/2.x/
db = SQLAlchemy()


# set up rest-x
# https://flask-restx.readthedocs.io/en/latest/quickstart.html
authorizations = {"basic_auth": {"type": "basic"}}
restx = Api(
    version="1.0",
    title="Ross Mountjoy Portfolio API",
    description="Get info from Ross Mountjoy's portfolio",
    authorizations=authorizations,
    prefix="/api/",
    doc="/api/",
)

# set up flask login
login_manager = LoginManager()
bcrypt = Bcrypt()


# set up flask admin
class AdminView(AdminIndexView):
    @expose("/")
    def index(self):
        return self.render("admin/admin_home.html")

    def is_accessible(self):
        return current_user.is_authenticated

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for("user_system.login"))


admin = Admin(
    name="Ross Mountjoy's Portfolio Database",
    template_mode="bootstrap3",
    index_view=AdminView(),
)


# Lazily initialize the flask extensions
def register_extensions(app):
    db.init_app(app)
    restx.init_app(app)
    login_manager.init_app(app)
    bcrypt.init_app(app)
    admin.init_app(app)


# register the blueprint modules
def register_blueprints(app):
    from app.api import api

    app.register_blueprint(api, url_prefix="/api")

    from app.site import site

    app.register_blueprint(site)

    from app.user_system import user_system

    app.register_blueprint(user_system)


# set up the database
def configure_database(app):
    @app.before_first_request
    def initialize_database():
        db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove()


def create_app(config_name):
    """
    Factory to create Flask application context using config option found in
    app.config

    :param config_name: (string) name of the chosen config option
    :return app: (Flask application context)
    """
    logging.basicConfig(
        filename="app.log",
        filemode="w",
        format="%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        level=logging.INFO,
    )

    app = Flask(__name__)
    app.config.from_object(config[config_name])
    logging.info("App initialized.")
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)

    return app

app/api/__init__.py
from flask import Blueprint

api = Blueprint("api", __name__)

from . import endpoints

app/site/__init__.py
from flask import Blueprint

site = Blueprint('site', __name__)

from . import routes

app/site/routes.py
from flask import render_template
from . import site
from resume import Resume

resume = Resume()


@site.route("/", methods=["GET"])
def index():
    return render_template("index.html", resume=resume)

app/user_system/__init__.py
from flask import Blueprint

user_system = Blueprint("user_system", __name__)

from . import models, routes

app/user_system/routes.py
from flask import render_template, redirect, url_for, request
from flask_login import current_user, login_user, logout_user
from app import db, login_manager, bcrypt
from . import user_system
from .models import User
from .utils import create_user


@user_system.before_app_first_request
def add_default_user():
    # create default user
    if not User.query.first():
        create_user(username="admin", password="admin", role="admin")


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@user_system.route("/login", methods=["GET"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("admin.index"))
    return render_template("user_system/login.html")


@user_system.route("/check_login", methods=["POST"])
def check_login():
    username = request.form.get("username")
    password = request.form.get("password")
    remember = request.form.get("remember")

    user = User.query.filter_by(username=username).first()
    if not user:
        return "User not found"
    if bcrypt.check_password_hash(user.password, password):
        login_user(user, remember=remember)
    else:
        return "Password is wrong"
    return "success"


@user_system.route("/logout", methods=["GET"])
def logout():
    logout_user()
    return redirect(url_for("user_system.login"))

app/templates/global/base.html
<!DOCTYPE html>
<html id="html" lang="en" data-textdirection="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title></title>
    <link rel="apple-touch-icon" href="static/images/favicon/apple-touch-icon-152x152.png?v=2">
    <link rel="shortcut icon" type="image/x-icon" href="static/images/favicon/favicon-32x32.png?v=2">
    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/material-icons.css">

    {% block page_lvl_css %}{% endblock page_lvl_css %}
</head>

<body id="body">
    {% block header %}{% endblock header %}

    {% block sidenav %}{% endblock sidenav %}

    {% block content %}{% endblock content %}

    {% block footer %}{% endblock footer %}

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js"
            integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD"
            crossorigin="anonymous"></script>

    {% block page_lvl_js %}{% endblock page_lvl_js %}
</body>

</html>

app/templates/user_system/login.html
{% extends "global/base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center" style="margin-top: 30vh">
            <div class="col-sm-12 col-md-6 col-lg-4">
                <form id="loginForm">
                    <div class="alert alert-info" role="alert">
                        Default Login is admin:admin
                    </div>
                    <div id='loginError' class="alert alert-danger d-none" role="alert">
                        A simple danger alert—check it out!
                    </div>
                    <div class="mb-3">
                        <input name="username" type="text" class="form-control" placeholder="Username">
                    </div>
                    <div class="mb-3">
                        <input name="password" type="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-check form-switch mb-4">
                        <input name="remember" class="form-check-input" type="checkbox" id="rememberMeCheck">
                        <label class="form-check-label" for="rememberMeCheck">Remember me</label>
                    </div>
                    <div>
                        <input class="btn btn-primary btn-block" type="submit" value="Login">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        const checkLoginUrl = "{{ url_for('user_system.check_login') }}";
        const mainUrl = "{{ url_for('admin.index') }}";
    </script>
    <script src="static/js/user_system/login.js"></script>
{% endblock %}